# !!! ================ 素材部分（游戏ID）
1056,:
  lower: 0.25
  upper: 0.4

1145,:
  lower: 0.25
  upper: 0.4

# !!! ================ 监控部分（游戏ID+媒体ID）
# 头条丨末日（大类）
1056,10:
  create_cost_an: 50
  create_cost_ios: 100
  pay_cost_an: 3000
  pay_cost_ios: 3800
  roi_an: 0.0196
  roi_ios: 0.0105
  roi_an_3: 0.0483
  roi_ios_3: 0.0330
  roi_an_7: 0.0982
  roi_ios_7: 0.0733
  budget_an: 3000
  budget_ios: 3000

# 广点通丨末日（大类）
1056,16:
  create_cost_an: 80
  create_cost_ios: 180
  pay_cost_an: 3800
  pay_cost_ios: 8000
  roi_an: 0.0196
  roi_ios: 0.0105
  roi_an_3: 0.0483
  roi_ios_3: 0.0330
  roi_an_7: 0.0982
  roi_ios_7: 0.0733
  budget_an: 3000
  budget_ios: 3000

# 百度丨末日（大类）
1056,45:
  create_cost_an: 30
  create_cost_ios: 150
  pay_cost_an: 2000
  pay_cost_ios: 5800
  roi_an: 0.0196
  roi_ios: 0.0105
  roi_an_3: 0.0483
  roi_ios_3: 0.0330
  roi_an_7: 0.0982
  roi_ios_7: 0.0733
  budget_an: 3000
  budget_ios: 3000


# 头条丨帝国（大类）
1112,10:
  create_cost_an: 160
  create_cost_ios: 450
  pay_cost_an: 2200
  pay_cost_ios: 6500
  roi_an: 0.0176
  roi_ios: 0.0212
  roi_an_3: 0.0293
  roi_ios_3: 0.0357
  roi_an_7: 0.0491
  roi_ios_7: 0.0597
  budget_an: 3000
  budget_ios: 3000

# 广点通丨帝国（大类）
1112,16:
  create_cost_an: 210
  create_cost_ios: 460
  pay_cost_an: 3300
  pay_cost_ios: 6000
  roi_an: 0.0176
  roi_ios: 0.0212
  roi_an_3: 0.0293
  roi_ios_3: 0.0357
  roi_an_7: 0.0491
  roi_ios_7: 0.0597
  budget_an: 3000
  budget_ios: 3000

# 百度丨帝国（大类）
1112,45:
  create_cost_an: 120
  create_cost_ios: 220
  pay_cost_an: 2800
  pay_cost_ios: 4500
  roi_an: 0.0176
  roi_ios: 0.0212
  roi_an_3: 0.0293
  roi_ios_3: 0.0357
  roi_an_7: 0.0491
  roi_ios_7: 0.0597
  budget_an: 3000
  budget_ios: 3000

# 百度丨炼仙（大类）
1145,45:
  create_cost_an: 60
  create_cost_ios: 200
  pay_cost_an: 900
  pay_cost_ios: 1000
  roi_an: 0.08
  roi_ios: 0.08
  roi_an_3: 0.23
  roi_ios_3: 0.23
  roi_an_7: 0.38
  roi_ios_7: 0.42
  budget_an: 1000
  budget_ios: 1000

# !!! ================ 计划部分（游戏ID+媒体ID+平台ID）
# 头条丨帝国纪元：单机加强版-联运
1001862,10,1:
  cpa_bid: [680,700]  # 非NOBID出价
  budget: 3300
  roi_goal: 0.012
  plan_auto_task_id: "11002,10998,12527"
  op_id: 13268
  web_url: "https://www.chengzijianzhan.com/tetris/page/7063028891002175495/"

# 广点通丨帝国纪元：单机版-广点通-联运
1001834,16,1:
  brand_name: "帝国纪元：单机版"
  brand_img: 116844
  bid_amount: [79888,80888,81888]
  daily_budget: 500000
  promoted_object_type: "PROMOTED_OBJECT_TYPE_APP_ANDROID"
  promoted_object_id: 2000001901
  plan_auto_task_id: "11427,10998,12063"
  op_id: 13268
  game_name: "帝国纪元"
  page_type: "PAGE_TYPE_TSA_APP"
  page_id_dict: {11917:{'page_id': '48805228'}, 
                 11918:{'page_id': '48805667'}, 
                 11538:{'page_id': '37672110'}}  # 增量字典
  expected_roi: 0.015

# 广点通丨帝国纪元-广点通-联运
1001994,16,1:
  brand_name: "帝国纪元" 
  brand_img: 70016
  bid_amount: [78888,80888,82888]
  daily_budget: 500000
  promoted_object_type: "PROMOTED_OBJECT_TYPE_APP_ANDROID"
  promoted_object_id: 2000005779
  plan_auto_task_id: "11427,10998,12063"
  op_id: 13268
  game_name: "帝国纪元"
  page_type: "PAGE_TYPE_XIJING_QUICK"
  page_id_dict: {11537:{'page_id': '59980407'}, 
                 11538:{'page_id': '59981115'}}  # 增量字典
  expected_roi: 0.015


# 百度丨罗马：单机加强版-百度-联运
1001794,45,1:
  brand: "罗马：单机加强版"
  plan_auto_task_id: "12550,12549"
  op_id: 13268
  game_name: "罗马：单机加强版"
  deepTransTypes: [26]
  subject: 1
  device: 1
  sex: 2
  age: "2,3,4,5"
  customAge: "25,99"
  keywords: ""  # !!! 改后台取
  transFrom: 1
  payMode: 1
  ocpcLevel: 2
  isSkipStageOne: True
  optimizeDeepTrans: [0.95,0.05]
  ocpcBid_F: [3300.00, 3400.00]
  ocpcBid_T: [180.00, 190.00]
  deepOcpcBid: [5800.00, 6000.00]
  ftypes: [1, 2]
  roiRatio: 0.05
  materialstyle: 109
  subtitle: "福利码：ch666"
  userPortrait: "https://feed-image.baidu.com/0/pic/1256783882_-2000210126_1902099700.jpg"
  bgtctltype: 2
  schedule: [{
             "weekDay": 3,
             "startHour": 5,
             "endHour": 10},
            {
             "weekDay": 4,
             "startHour": 5,
             "endHour": 10}]


# 头条丨幸存者挑战2-联运
1001703,10,1:
  cpa_bid: [750, 800]  # 非NOBID出价
  budget: 3300
  roi_goal: 0.012
  plan_auto_task_id: "11002,10998,12098"
  op_id: 13268
  web_url: "https://www.chengzijianzhan.com/tetris/page/7127204719681159175/"


# 百度丨幸存者挑战-联运
1001379,45,1:
  brand: "幸存挑战"
  plan_auto_task_id: "12550,12623"
  op_id: 13268
  game_name: "幸存挑战"
  deepTransTypes: [26]
  subject: 1
  device: 1
  sex: 2
  age: "2,3,4,5"
  customAge: "25,99"
  keywords: ""
  transFrom: 1
  payMode: 1
  ocpcLevel: 2
  isSkipStageOne: True
  optimizeDeepTrans: [0.95,0.05]
  ocpcBid_F: [3300.00, 3400.00]
  ocpcBid_T: [180.00, 190.00]
  deepOcpcBid: [5800.00, 6000.00]
  ftypes: [1, 2]
  roiRatio: 0.05
  materialstyle: 113
  subtitle: "烧脑闯关，你能过几关？"
  userPortrait: ""
  bgtctltype: 2
  schedule: [{
             "weekDay": 3,
             "startHour": 5,
             "endHour": 10},
            {
             "weekDay": 4,
             "startHour": 5,
             "endHour": 10}]

# 百度丨炼仙传说-国内-联运
1001900,45,1:
  brand: "炼仙传说"
  plan_auto_task_id: "12550"  # 临时
  op_id: 13268
  game_name: "炼仙"
  deepTransTypes: [26]
  budget: 2000

  subject: 3
  device: 2
  sex: 0
  age: "2,3,4"
  transFrom: 1
  payMode: 1
  ocpcLevel: 2
  isSkipStageOne: True
  optimizeDeepTrans: [1.0,0.0]  # 决定跑法是付费-付费roi、激活-付费
  ocpcBid_F: [1500.00, 1600.00]
  ocpcBid_T: [80.00, 100.00]
  deepOcpcBid: [800.00, 1000.00]
  ftypes: [[1, 2], [1, 2, 8]]  # 版位
  roiRatio: 0.042
  materialstyle: 113
  subtitle: "挂机炼仙战力逆天"
  userPortrait: "https://feed-image.baidu.com/0/pic/174923032_-1742827595_1474413796.jpg"
  keywords: [
    "仙路至尊,免费下载,全文免费阅读,游戏三张牌下载,三国赵云手游,梦幻仙侠官方手游,9游梦幻西游,斗罗大陆 漫画,天龙八部领武圣卡,斗破苍穹手游世界等级,末日求生,捕鱼游戏下载,苹果8,游戏礼包领取,手游三国名将攻略,天龙八部手游大礼包,唐三斗罗大陆,斗罗大陆页游,梦幻西游手游神器任务,斗罗大陆龙王传说手游,风云手游,新斗罗大陆手游,梦幻西游开区表,推荐手游,暗黑破坏神3,仙侠萌主手游,三国群英传1单机版,穿越言情小说,大话手游大将军,极品修真,二次元卡牌游戏,下载网游,龙王传说3斗罗大陆,下载王者荣耀,网游三国游戏排行榜,修仙小说排行榜完结,修仙修仙,仙侠江湖手游礼包,凡人仙界篇,天龙八部原文,无双手游,凡人修真2公益服,征途手游礼包,斗罗大陆3龙神传说,动漫制作,斗罗大陆游戏礼包,快播官网,三国武将,啪啪三国游戏,三国群英传单机,仙侠游戏美女角色,海贼王吧,斗罗大陆之龙王,逍遥西游,龙图三国手游,仙侠江湖,安卓游戏手机,看片网站,手游版梦幻西游,dnf更新,手游平台,耐玩三国卡牌游戏,灭世战神手游,刀塔英雄,斗罗大陆3龙王传说结局,开什么店赚钱,修仙结婚游戏,西游降魔篇,史莱克七怪,梦幻西游兽哥,仙侠礼包,天龙八部租号,卡牌游戏排行榜,暗黑大冒险手游攻略,最新手游排行榜,大话西游手游,江湖大话西游,戮仙,梦幻仙侠手游下载,梦幻修仙,动漫原画,app,斗罗大陆2绝世唐门小说,天崖,大话西游手游官网,世界上最好玩的游戏,剑魂,网游回合制游戏,斗罗大陆漫画全集,梦幻西游手游官网,三国卡牌,h漫画,天龙八部手游挂机,修真界败类,魂斗罗归来手机游戏,关于手游三国卡牌游戏,仙侠恋小说,斗罗大陆ol,梦幻西游手游神器任务,精灵宝可梦,变态游戏,卡牌游戏,大话西游手游礼包龙马,卡牌手游哪个好玩,斗罗大陆之龙王传说,梦幻加强版,网游仙侠之大主宰,红警手机版单机版下载,天龙八部圣兽山宝箱,修仙小说,卡牌回合网游,斗罗大陆3龙王传说游戏,倚天屠龙记手游,斗罗大陆漫画免费,暗黑战神,斗破苍穹小说下载,回合制手游排行榜,帝吧,天龙八部充值网址,逍遥西游,二战地图,最新修仙手游,三国国战游戏,古剑奇侠,卡牌类游戏,斗破苍穹小说免费阅读,暗黑破坏神单机版,免费全本小说阅读,口袋妖怪3ds,三国 手游,帝王三国手机版,天龙八部小说金庸,斗罗大陆3龙王传说单机版,dnf游戏下载,传奇手游深渊,不灭武尊,梦幻西游武神坛,天龙八部天佛降世,游戏游戏,斗罗大陆漫画2绝世唐门小说,西游女儿国手游下载,游戏魂斗罗归来,梦幻加强版,游戏吧,大作战,最新手游排行榜,信仰大爆炸,抽卡游戏,手游最新排行榜,仙剑奇缘,回合制游戏下载,二次元卡牌游戏,仙侠网游,传奇手游下载,斗罗大陆单机游戏,足球手游,梦幻手游,希腊神话,最新回合手游,手游逍遥西游手游,恋爱养成小游戏,手游网络游戏,三国乱世武将,仙侠手游情侣名,天龙八部黄日华版,刀剑神域卡牌游戏,有坐骑的网络游戏,穿越火线手游,修仙劫手游攻略,手机单机版游戏,魔域阿卡玛之魂哪里爆率高,好看的总裁小说,天龙八部搜狐充值,英雄无敌3,三国第一猛将并非吕布,修仙表情,3d手游排行榜前十名,免费漫画软件,暗黑破坏神修改器,梦幻西游新,手游大话西游,红警手机版单机版下载,绝地求生全军出击,无限恐怖,游戏打装备的游戏,斗罗大陆小游戏,魂斗罗,唯美仙侠手游,动画片,3d魔幻手游,江湖外传之天龙八部,征途,格斗,仙侠手游装备升级,dnf手游,角色扮演仙侠手机游戏,网游三国,游戏修仙物语,斗破苍穹之妃花仙,成龙,大话西游神天兵,斗罗大陆手机版,网游之网游,dnf游戏,大话西游二大话精灵,女生仙侠手游,传奇 手游,斗罗大陆之剑,角色扮演游戏手游,斗战神,斗罗大陆漫画全集,卡牌类手游,三国类的游戏,最火的卡牌手机游戏,卡牌类三国手机网游,放置江湖,4399生死狙击,征途角色,最强武侠手游,斗罗大陆绝世唐门小说免费,全能学生,恐龙快打,三国之召唤猛将,像三国手游下载,地下城与勇士手游下载,妖神记,梦幻西游巫蛮儿武器,情侣仙侠游戏,斗罗大陆第2部,三国类手游哪个最好玩,凡人修真,快递单号查询,无极修仙的手游,17173,凡人修仙传小说,逆天邪神最新章节,封号斗罗手游,网易三国手游,h小说在线阅读,斗罗大陆后传,刀剑乱舞,游戏二次元游戏,坦克,天龙八部轮回服网址,梦仙侠,斗破苍穹小说免费阅读,惊天动地手游,梦幻西游手游帮派任务,诛仙 手游,斗罗大陆龙王传说游戏,斗罗大陆3小说免费阅读全文,龙王传说漫画,h小说在线阅读,王者荣耀杨戬,养成卡牌手游,梦幻西游互通版,斗破苍穹小说下载全集,征途,唐家三少新书,极武尊手游,仙侠游戏下载,看大片,天狂传说斗罗大陆,三国的游戏,大劫主,二战坦克,手机游戏排行,传奇序章,混沌剑神,策略战争,仙逆,火影,大型仙侠游戏排行榜,三国群英传2,龙之谷,仙侠修真手游,仙界修仙,斗罗大陆ii绝世唐门,梦幻西游动画片,斗罗大陆之雷霆斗罗,冒险岛手游哪个角色不花钱,手机网游卡牌游戏排行榜,斗罗大陆小说免费阅读,免费完结全本小说,回合制手游排行榜,好玩的卡牌网游,军师三国手游,免费视频,手游挂机传奇礼包,rpg游戏下载,畅游天龙八部,txt免费小说,剑神诀手游下载,西游q记,三国游戏,lol手游版,大话西游手游无限仙玉,开什么店赚钱,老公宠妻太甜蜜 小说,仙侠手游下载,三国手游排行榜,新大话西游2,斗破苍穹,大话西游手游炼狱副本,格斗类手游,绝世唐门斗罗大陆,择天记,三国攻城网游,搜狐网,大话西游歌曲,斗罗大陆神界传说2破解版,洪荒神话,大话西游歌曲,三国的网页游戏,破解版手机游戏,梦幻西游法宝,冒险岛游戏下载,梦幻西游本子,宠物游戏下载,攻城三国游戏,斗罗大陆电视剧,动漫游戏,番号,龙王,飞卢小说,斗罗大陆之剑,二次元萝莉,新斗罗大陆手游阵容,卡牌手游,不花钱卡牌手游,刷装备的仙侠游戏,手游龙战三国,武动乾坤,二战为什么要杀犹太人,破解版手机游戏,腾讯视频下载,楚汉传奇,3d,英雄无敌3死亡阴影单机战棋游戏,斗罗大陆绝世唐门漫画全集免费,手游武侠版,二次元手游卡牌游戏,pk厉害的手游,妖神记,凡人修仙传仙,使命召唤,怪物史莱克,梦幻西游手游双平台下载,卡片三国游戏,好玩的修仙手游,斗罗大陆神界传说2下载,斗罗之武魂觉醒手游,金庸,斗牛比赛,仙侠游戏啪啪,热门手游,小说推荐,魔兽世界攻略,斗罗大陆3d手游,修仙挂机,狂战天下手游,梦幻西游口袋版,大话西游2无限仙玉版,大话西游二大话精灵,超级玛丽,日本动漫,仙侠,梦幻西游神兽,手游交易平台,斗罗大陆之剑,斗罗大陆1游戏,穿越,梦幻西游手游倒金币,西游降魔篇,幽冥白虎,百度,梦幻西游手游版什么职业好,网易回合制游戏,修真游戏,车展,三国战吕布,冒险岛辅助技能,三国杀卡牌大全,手游大全,iphone,东方仙侠,大话仙侠手游,放开那三国礼包,耐玩的手机游戏,手游三国大军师,rpg,冒险过关手游,冒险手游单机,我的世界,三国战记,绝世唐门小说,单机版,天龙八部手游礼包激活码领取,斗罗大陆2绝世唐门漫画下载,大唐仙妖劫,畅游天龙八部手游,大话西游2官网下载,天龙八部手游所有礼包,梦幻西游手游礼包在哪里兑换,三国游戏下载,百度,二次元手游,变态游戏,七界武神,烈焰手游礼包,英雄联盟手机游戏,手游修仙排行榜,漫画,免费小说大全,海岛奇兵无限钻石版,斗罗大陆之神之子,三国杀卡牌大全,万古神帝,剑破仙惊,龙王传说起点,梦幻藏宝阁,我的美女总裁老婆,3d,快播下载,不朽凡人,两副牌斗地主,梦幻西游竖琴价格,仙剑诛仙手游,角色扮演仙侠手游,手游版dnf,火影,角色冒险手游,鬼吹灯手游,斗罗大陆神界传说2下载,极品修真,梦幻诛仙手游,卡片三国游戏,魂斗罗归来什么时候能玩,极武尊手游,火爆仙侠手游,合肥天气,魂斗罗归来魂斗罗战舰,动漫改编手游,封号斗罗,地下城与勇士小游戏,诛仙网游,修真归来,vivo,白蛇传说,焚天之怒,斗罗大陆4,修真类手游,修仙类网路网游,冒险岛之锤,手游三国卡牌游戏,斗罗大陆3龙王传说手游,三国武将游戏,传奇手游排行榜,斗罗大陆2绝世唐门小说全集,挂机刷装备手游,丧尸来了,梦幻西游发号,现在新的网络游戏,神雕侠侣手游,跨过千年来爱你小说,绝地求生攻略,斗破,名将三国志,都市小说,英雄联盟手游,三国卡牌,三国杀,凡人修真,将夜,凡人修仙全文阅读,网游辅助,3d手游排行榜前十名,放开那三国手游礼包,渡劫手游,手游模拟器,灵主手游,lol卡牌游戏,三国 人物,斗三国,石器时代手游,网站,仙侠修仙手游角色,斗罗大陆强者排名,三国类单机手机游戏,九游诛仙手游,游戏吧,仙侠情侣游戏,斗破,动漫改编手游,好玩的二次元手游,钓鱼游戏下载,游戏手机排名,三国 手游,三国类卡牌游戏,不朽神王,三国角色扮演手游,斗罗大陆龙王传说手游,免费在线小说,斗罗大陆2绝世唐门漫画下载,红警3,ios手游,三国游戏人物,天龙八部游戏技能,梦幻西游手游怎么转金币,格斗游戏,rpg,穿越火线手游版,斗罗大陆游戏武魂排名,武侠游戏排行榜,大话西游手游神兵获得,间谍的战争,手游修仙狂徒,大型副本手游,热门仙侠手游,暗黑2亚马逊,都市之最强纨绔,仙侠问道,仙侠手游rpg,刀剑神域,都市言情完结小说,梦幻西游手游补丁下载,打装备手游,青云诀手游好玩吗,手机网游,梦幻西游手游超级神兽打书,媚三国手游,斗罗大陆之七怪之子,卡牌类三国手机网游,暗黑西游游戏,梦幻仙侠手游下载,宇宙级大反派,武动乾坤手游,三国卡片游戏,仙侠小说,古代战争,江湖大话西游,卡片手游,生存战争游戏,倩女幽魂,官场小说,好玩手游排行榜,剑神诀手游下载,传奇手游手游,放置江湖,海贼王官方手游,最新手游排行榜,斗罗大陆2之绝世唐门,手游梦幻西游,三国游戏大全单机版,二战手游,武动乾坤手游,斗罗大陆绝世唐门手游官网,大白鲨游戏,龙王传说起点,绝地求生攻略,手游梦幻西游手游,有什么好玩的回合制手游,斗破苍穹小说下载,宠物小精灵,战斗手游,三国威力加强版,英雄联盟手游,万古天帝第一神,楚留香手游,苹果官网,梦幻西游手游礼包兑换码,新斗罗大陆手游攻略,魂斗罗归来组队翻牌,梦仙侠,仙侠类角色扮演网游,冒险岛3,戮仙,天狂传说斗罗大陆,魔法门之英雄无敌,混沌剑神,手游仙侠奇缘,qq红警大战,斗罗斗罗大陆,三国手游推荐,凡人修仙传仙,天龙八部刷怪脚本,圣墟小说,仙剑奇缘,神道丹尊,斗罗大陆魂斗罗,三国卡牌手游大全,养成卡牌手游,梦幻西游无双版手游,唐家三少新书,苹果,奇迹手游哪个职业厉害,梦幻西游手游口袋版,卡牌养成手游,突袭,妖精的尾巴,游戏手游仙侠,火影手机游戏,大型战争策略手游,传奇手游,卡牌手游,斗罗大陆2绝世唐门手游,街机三国,全民手游,艳遇修仙,冒险岛辅助技能,凡人修真网页游戏,小说全本免费,手游魔力宝贝,斗罗大陆手游下载,青云诀手游好玩吗,英雄战迹手游,梦幻西游360,斗罗大陆2免费阅读全文,新版诛仙手游,修仙传,寻仙手游,手游仙侠角色游戏,仙侠游戏角色,刀塔传奇游戏攻略,山海经,天龙八部限时活动,冒险岛3,乱世仙侠手游,梦幻西游手游技能,唐家三少小说,仙侠网游主题曲,刷装备的仙侠游戏,问道手游,斗罗大陆的封号斗罗,三国卡牌手游排行,手游卡牌游戏排行榜,三国策略手游,斗罗大陆ii绝世唐门,天龙八部真元,凡人修仙传 手游,魂斗罗归来手游,斗罗大陆游戏网游,赚钱,红警大战坦克,神谋三国,回到三国游戏,斗罗大陆3龙王传说结局,免费小说男欢女爱,大武侠,修仙恋爱手游,三国卡牌类手机网游,天刀,类似斗罗大陆,航母,手游网游,斗罗大陆1,斗战圣传,手机动漫卡牌游戏,武侠电视剧,三国游戏大全,斗罗大陆魂斗罗,免费小说大全,三国角色扮演网游,txt下载,4399游戏盒,免费回合制手游游戏,征途新服,凡人修仙传2,至尊,卡牌类游戏网游,角色冒险手游,仙侠角色扮演手游,剑侠世界手游官网下载,梦幻西游手游升级攻略,大话西游神天兵,武动乾坤 天蚕土豆 小说,高德地图,天龙八部公测了吗,魔兽世界,三国杀卡牌游戏,梦幻西游4天命之战,手机回合制网游排行榜,好玩的传奇手游排行榜,卡牌竞技游戏,佣兵手游,三国梦想,斗罗大陆神界传说游戏,爱情仙侠手游,三国志单机游戏,冒险岛手游双刀流云斩,斗罗大陆免费下载,万古独尊,非诚勿扰,仙侠网游主题曲,三国五虎将,捕鱼游戏下载,有没有类似梦幻西游的游戏,剑网三手游官网下载,游戏下载软件,梦幻西游开新区,那个网小说免费,音乐,魔域阿卡玛之魂哪里爆率高,三国类卡牌手机网游,热血江湖升级攻略,梦幻西游大电影,三国手游,古装仙侠游戏,斗罗大陆谢偕,斗罗之武魂觉醒游戏,手游冒险,斗罗大陆之神界传说,斗罗大陆绝世唐门小说,破解版安卓手机游戏下载,lol,三国吕布游戏,太古神王,手机,名将三国,镇魂,结婚的手游,刀塔英雄吧,超级魂斗罗30条命,3d魔幻手游,传奇游戏,航母,剑灵17173,魂斗罗归来下载地址,仙侠手游,大话西游手游无限仙玉,后宫恋爱游戏,逆天邪神,斗罗大陆之时空斗罗,梦幻西游手游双平台下载,剑网三手游,洪荒神话,真武侠手游,大海贼冒险岛,海贼王吧,三国兵力手游,梦幻西游手游合宠攻略,良心卡牌手游,神将三国,斗罗大陆神界传说2破解版,寂寞单身约会,仙侠类手游,灭世武修,魂斗罗归来组队翻牌,航海王启航,寂寞单身约会,精灵宝可梦,新天龙八部鬼谷什么时候出,大型战争策略手游,仙侠修仙,永夜君王,仙侠电影,卡牌游戏排行,dnf装备,斗罗大陆2绝世唐门漫画下载,宠文小说,斗罗大陆之神界传说,王者荣耀即将出的皮肤,曹彰,360借条,刀剑,动漫美女,有没有类似梦幻西游的游戏,魔兽rpg,梦幻西游手游礼包兑换码,武魂,极品家丁小说,手游冒险,天龙八部礼包兑换码,卡牌游戏手游排行榜,斗罗大陆2听书,乱世仙侠手游,手游暴走仙侠,斗罗大陆之炎帝斗罗,西游q记,斗罗大陆2免费阅读全文,二次元,重生,女生仙侠网游,人气回合制网游,剑侠情缘手游手游,魔兽世界,剑网三手游官网下载,三国乱世,斗罗大陆3龙王传说3,今日头条,冒险岛手游防御力,梦幻西游无双版下载,赛睿暗黑3,美女,斗罗大陆3龙神传说,足球手游,有坐骑的网络游戏,无极修仙,斗罗大陆2人物,王者荣耀干将莫邪,角色仙侠手游,情侣仙侠游戏,类似帝王三国手游,dnf韩服,手机,手游大作,惊天动地手游,海战,仙侠爆装备的手游,斗罗大陆等级,梦幻西游藏宝阁,卡牌游戏推荐,汽车之家,rpg手游,征途礼包领取,火影忍者手游,斗罗大陆之兽神,微信支付,手游修真诀礼包,绝世唐门手游,修罗,仙侠同人小说,三国手机游戏,手游斗罗大陆,斗罗大陆绝世唐门王冬,绝地求生大逃杀,的小说,手游修真诀礼包,大话西游手游开服表,火影忍者ol,三国世界,梦幻西游充值卡,斗罗大陆之炎帝斗罗,好玩的修仙手游,倚天屠龙记手游,剑来 小说,3d手游排行榜前十名,冒险岛手游双刀尖兵,三国战斗游戏,梦幻西游手游吧,斗破苍穹小说免费阅读,血族bloodline手游,策略类卡牌游戏,冒险类型手游,冒险岛手游哪个角色不花钱,dnf剑神,好玩的网页游戏,妖怪正传,网游之三国领主模式,灭霸神魔录手游,口袋版梦幻西游帮派任务,仙侠角色手游,手游仙侠奇缘,斗罗大陆h,斗罗大陆游戏武魂,微信,英雄无敌3最强隐藏英雄,斗罗大陆2绝世唐门,红色警戒手机版,魂斗罗手游什么时候公测,暗黑血统2,卡牌类三国手游,人气高的魔幻手游,修仙问情篇,角色扮演的手游,仙剑手游,魔域永恒,暗黑风游戏,热血帝王三国,什么手游装备全靠爆,梦幻西游宠物进阶,仙侠之我有一口棺,诛仙,武道至尊,类似手游,绝世剑神,冒险类手游,超级玛丽,巨神战击队2,修仙表情,qq仙侠传,钓鱼,唐家三少小说,格斗游戏,凡人修仙手游论坛,帝王三国2,有没有卡牌回合游戏,斗罗大陆2漫画,梦幻西游手游交易猫,什么小说软件好用又免费,游戏大厅,全文阅读,斗罗大陆阅读全文,看片网站,重生,网游三国游戏排行榜,书旗小说,手游传奇装备,英雄联盟卡牌,斗罗大陆漫画免费,动漫斗罗大陆,绝地求生大逃杀,免费,今日公测手游,剑侠情缘,仙侠修仙,修真界败类,像冒险岛的手游,小游戏,现在还有天龙八部荣耀服吗,奥特曼游戏,dnf征战者刷图加点,冒险岛挂机伴侣,游戏动漫,手游三国名将武将搭配,dnf加点模拟器,修真者玩网游,从哪看到天龙八部充值,大主宰手游,类似阴阳师的抽卡游戏,梦幻西游手游倒金币,漫画书,刀塔传奇手游,破解版游戏大全,游戏对战平台,问道手游下载,格斗类手游,地下城勇士,亚洲,宠物小精灵之,古风仙侠游戏,凡人修仙之风云再起,斗罗大陆游戏攻略,妖精的尾巴,动漫美女图片,武侠手游排行榜,三国杀卡牌数,战舰世界手游,情侣仙侠手游,打怪升级的手游,网游之三国领主模式,刀剑,神藏,帝国手游,蔡徐坤,魂斗罗归来,盟军敢死队,王者荣耀吧,凡人修真手机版,帝国时代3下载,梦幻西游口袋版,手机卡,洪荒,斗罗大陆之雷霆斗罗,荒岛求生,地下城与勇士手游下载,宠物小精灵手游,手游魔力宝贝,小说推荐,神武手游,惊天动地手游,卡牌三国神将传,二次元游戏女主角,万域灵神,斗罗大陆3龙王传说漫画,dnf鬼泣吧,三国乱世国战任务,人气回合制网游,地下城与勇士,凡人修真2游戏名字,大话西游手游礼包龙马,游戏本,手游排行榜,秦时明月,梦幻西游官网序列号,修仙表情,游戏手机排名,经典魂斗罗手游,回到明朝当王爷小说,刀塔传奇360版下载,仙侠修仙手游,三国战争手游,冒险岛2,宠物游戏,间谍的战争,天龙八部萧峰,二战地图,修仙狂徒女名字,部落冲突,勇士觉醒,什么卡牌手游好玩,斗罗大陆手游公测,仙侠小说,梦幻西游攻略,战争剧,策略类的手游,天龙八部,网游仙侠小说,百战天下,刀塔传奇机枪兵,伊拉克战争,十大手游排行榜,凡人修仙全文阅读,北京天气,三国卡牌,修仙无双手游礼包,仙尘ol,仙界修仙,激战2,手游下载排行榜,仙侠手游战斗,手游三国乱世,手游网络游戏,小说阅读免费,游戏手游,梦幻修仙,梦幻西游快速下载,街机三国手游礼包兑换,卡牌游戏圣斗士星矢,斗罗大陆电视剧,梦幻西游手游版什么职业好,风云手游,冒险岛手游好玩吗,斗罗之扇子武魂,二次元,恋爱养成游戏,极道天魔,新开三国游戏,情话,模拟人生,数码大冒险,东方仙侠,大话西游飞升是什么,仙侠手游,仙侠游戏手游,冒险,梦幻手游辅助技能,天龙八部神将,斗破苍穹辛亚雷,万古至尊,梦幻西游手游语音权限,地下城与勇士游戏,什么卡牌手游好玩,海贼王手游,安卓手机游戏,斗罗大陆手游,古风仙侠游戏,火爆仙侠手游,斗罗大陆2绝世唐门主题曲,游戏修仙手游,最新的角色扮演手游,像三国手游礼包,热血传奇手游,奇兵,苹果8,dnf吧,口袋版梦幻西游帮派任务,dnf手机游戏,手游下载排行榜,仙侠情缘手游,小说软件,腾讯视频,大话西游浑天,穿越诸天,间谍的战争,魔兽世界壁纸,三国志,凡人修真2公益服,dnf更新,斗罗大陆的封号斗罗,点将三国,仙侠题材手游,魔兽,武侠仙侠,小说下载,天龙八部手游更新时间,试剑苍穹,仙侠奇谭手游,剑网3手游版,最新仙侠手游,龙王传说起点,app,唐家三少,三国之召唤猛将,航海王剧场版,一念永恒耳根,回合rpg游戏,绝世仙王,武碎仙侠,最新回合制手游,帝王三国手机版,斗罗大陆漫画2,真武大帝,斗罗大陆谢偕,魂斗罗手游武器攻略,梦幻西游游戏礼包,三国游戏大全,斗战狂潮,军师三国手游攻略,礼包,西游女儿国手游下载,斗罗大陆2绝世唐门小说全集,车展,卡牌手机游戏,梦幻西游手游九游,斗罗大陆之小舞乳喷,魔域阿卡玛之魂哪里爆率高,凡人修仙之修仙篇,二战手游,最火爆的仙侠手游,凡人修仙传仙界篇,魔兽历史,回合手游,杀神手游,玩仙侠手游,漫威未来之战,网游三国之升级武将,传奇手游爆率,三国的游戏,梦幻西游无双版下载,日本动画,看片网站,梦幻西游龙太子武器,冒险岛爆率,冒险岛之锤,凡人修仙传之仙界篇,仙魔,梦幻西游网易版官网,新征途礼包,类似于天龙八部的手游,梦幻仙侠手游攻略,霍雨浩,dnf鬼泣吧,斗罗大陆成神之路小说,可以结婚的仙侠手游,人气二次元游戏,洪荒,腾讯游戏手游,三国卡牌英雄,神墓,斗罗大陆后传,斗罗大陆之神界传说,神兽,全靠打怪爆装备的手游,暗黑破坏神单机,传奇手游装备,渡劫天功,修仙狂少,至尊武神,游戏对战平台,飘渺修仙加强,剑网三,天狂传说之斗罗大陆,游戏手机游戏,西游修仙传手游,三国卡牌手游排行榜,手游冒险,dnf官方手游,绝世唐门漫画,战争大流氓,魔兽秘籍,刀塔传奇主页,赚钱,街机,梦幻西游客户端下载,天堂2,在线卡牌游戏大全,三国卡牌类型游戏,宠物手游,三国卡牌手游游戏,仙侠剑,王者荣耀杨戬什么时候出,修仙修仙手游,仙侠武侠,凡人飞仙传,天龙八部手游官网,手游神将三国,红警大战冰霜坦克,血族bloodline手游,穿越言情小说,捕鱼,仙侠礼包,女生仙侠网游,英雄杀卡牌游戏,凡人修仙之风云再起,勇士觉醒,三国卡片游戏,天龙八部什么时候公测,万古至尊,回合制手游网游排行,地下城手游,斗罗大陆页游,御龙在天手游,游戏加速器,魔兽归来,斗罗大陆2绝世唐门吧,技能,冒险,类似三国,西游降魔篇,冒险类手游,镇魂,仙侠虐心小说,梦幻手游交易平台,焚天之怒,类似斗罗大陆的游戏,手机梦幻西游2,太古神王,斗罗大陆3龙王传说txt,斗破苍穹电视剧,南昌天气,武侠的手游,狮子座,仙侠修真手游,梦幻西游手游角色,万域灵神,梦幻西游手游口袋版,斗罗武魂,4399凡人修真,吃鸡,大话修仙变态,梦幻西游手游几个版本,梦幻西游金币充值,斗罗之武魂觉醒手游,网游之三国领主模式,诸天最强大佬,御龙在天手游,单机版,2048游戏下载,大话西游手游神兽排行,一款三国手游,手游魔力宝贝,放置奇兵吧,礼包,斗罗大陆 2,梦幻修仙,小说下载,绝世唐门小说,斗罗大陆网游,热门仙侠手游,奥迪,暗黑破坏神2符文之语,天龙八部手游丐帮,凡人修真2天神战场,剑三手游,搞笑仙侠小说,天龙八部官网,天龙八部赠点怎么获得,修真界败类,手游龙战三国,刀塔传奇变态版,好玩的卡牌手游,天龙八部特权,刀塔传奇pc,卡牌怎么玩,斗罗大陆之创世神,热血江湖升级攻略,有声小说,武庚纪,互动游戏,幸存者,大话西游哪吒,女神卡牌游戏,天龙八部原文,宫廷手游,好看的小说推荐,梦幻西游大电影,梦幻西游开新区,rpg游戏下载,手游凡人修仙传,斗罗大陆全文,修仙者,风云手游,三国下载,军师三国卡牌,斗罗大陆之创世神,北京天气,天龙八部赠点怎么获得,最近公测的手游,网游之,腾讯视频,dnf官网,三国类手游卡牌,绝地求生,三国单机游戏,斗罗大陆,玛莎拉蒂,不要钱的卡牌游戏,卡牌回合制手游,魔兽世界和天龙八部,仙侠奇谭手游,石器时代手游,小说下载,热门游戏手机游戏,免费官场小说,卡牌三国ol,天龙八部手游福利礼包,古代言情完结小说,仙侠江湖,战争策略类手游,dnf剑圣,仙侠礼包,三国游戏大将军,dnf剑圣,水浒q传,斗罗大陆2之绝世唐门小说,好玩的仙侠手游,天龙八部手游新区开服表,绝地求生全军出击,大话仙侠,冒险岛辅助技能,手游三国杀礼包,西游降魔篇手游礼包,明朝初年,新世界动漫,txt免费小说,暗黑破坏神2符文之语,梦幻西游服战,斗罗大陆之淫邪小舞,斗罗大陆漫画3,狗狗,大话西游飞升是什么,逍遥西游九游版,仙侠有声小说,2018手游排行榜,少年仙侠手游下载,斗破苍穹之无上之境,搜狐视频,冒险岛技能,梦幻诛仙手游,剑破仙惊,三国,梦幻天劫,斗罗大陆2手游,三国战斗游戏,征途角色,青云诀手游好玩吗,三国游戏单机版,手游三国系列,大话西游2官网下载,啪啪仙侠游戏,安卓手机游戏下载,回合手游,免费全本小说阅读,网游,凡修仙,梦幻西游互通版,2018王者荣耀限定皮肤免费领软件,穿越诸天,斗罗大陆2绝世唐小说,金庸作品,单机版游戏,口袋妖怪,烈焰手游礼包,二战片,勇士觉醒,qq仙侠传,斗罗3龙王传说小说,妖怪正传,大圣之怒,凡人修仙传小说,仙剑奇缘,梦幻西游特效,三国卡牌手游排行榜,多人玩卡牌游戏,天龙八部怎么挂机,技能,挂机刷装备手游,斗罗武魂,玄幻手游手游,斗罗大陆漫画书,西游梦幻,大话西游手游玄武神兽,梦幻西游游戏礼包,免费完结全本小说,凡人修仙传之仙界篇,斗罗3龙王传说小说,梦幻西游360,三国乱世,新天龙八部吧,冒险手游单机,斗罗大陆小游戏,卡牌类三国手游,暗黑破坏神2符文之语,南昌天气,媚三国手游,仙逆手游,刷装备的仙侠游戏,神将世界手游,斗罗大陆小说免费阅读,3d,冒险岛爆率,玄幻小说,斗罗大陆游戏武魂排名,刷副本爆装备的手游,传奇类游戏,大话官网,天刀,游戏中心,斗破苍穹电视剧,dnf剑神,奔驰,冒险岛伴侣挂机地点,三国手游卡牌,三国杀手游礼包,重生之独宠无二,三国杀神将,群侠传,秦时明月手游,魔兽剑圣,梦幻西游手游转武器,流浪的蛤蟆,新斗罗大陆礼包,网游作者,动漫制作,梦幻西游手游无双版,梦幻西游360,战争指挥官,凡人修仙传之仙界篇,手游配音,大话西游无限仙玉,怪物猎人2,天龙八部充值网址,梦幻西游礼包兑换码,人气高的魔幻手游,鱼竿,东方仙侠,天龙八部升级经验,下载斗地主游戏,校花的贴身高手,仙界手游,梦幻西游论坛,言情小说,仙侠修仙手游大作,斗罗大陆之斗魂大陆,仙侠动作手游,英雄联盟卡牌,红警3,斗三国,求战争策略类手游,梦幻西游无双版礼包,放开那三国,红警坦克,废材少爷玄幻小说,穿越仙侠世界,斗罗大陆三龙王传说小说,西游手游角色,三国杀卡牌游戏,大武侠,王牌御史,梦幻西游兽哥,斗罗大陆虐心,三国群英传2,次元大作战充值,武侠游戏,手游青云决好玩吗,大型仙侠游戏排行榜,超变传奇手游,斗罗大陆之剑,万界天尊,装备全靠打的手游,大战僵尸,正版传奇手游,小说下载,冒险岛手游官网,破解版手机游戏,免费完结全本小说,九龙神鼎,仙侠修真手游,三国卡牌游戏带国战的,小说软件下载排行榜,斗罗大陆阅读全文,女神卡牌游戏,仙侠情手机游戏,梦幻西游论坛礼包,斗罗大陆之绝世唐门,策略类卡牌游戏,手游逍遥西游手游,卡牌杀,手游大作,捷信贷款,凡人修仙传仙界篇忘语,暗黑3,巨神战击队2,手机网游,手机三国,街机三国许褚,试剑苍穹,暗黑血统2,模拟人生,封号斗罗,h1z1大逃杀,英雄战魂,手游传奇装备,cf手游,魂斗罗游戏,斗罗大陆游戏礼包,仙侠游戏手游,修罗武神,二次元游戏什么好玩,大话西游神天兵,凡人飞仙传,小说之斗罗大陆,修仙狂徒女主角绿帽,小米手机,武侠仙侠,腾讯手游,天涯明月刀手游,动漫手机卡牌类游戏,帝王三国2,单身交友群,类似暗黑的手机游戏,洪荒,进击的丧尸,捕鱼,啪啪三国手游官网,斗罗大陆单机游戏,金庸武侠手游,天龙八部手游丐帮,热血江湖手游,天龙八部手游礼包大全,龙王传说下载,三国名将传手游,莽荒纪,不思议迷宫,最新的全本玄幻小说,结婚的手游,剑道独尊,战争剧,大话西游无限仙玉,手游天龙八部礼包,二次元游戏手游,免费阅读小说,三国群英传单机,帝王三国手游,仙侠手游仙侠手游,征途新服,刀剑,剑侠世界手游下载,十大手机游戏排行榜,手游充值平台,斗罗大陆之创世斗罗,策略战争,丧尸来了,游戏王手游,丧尸之战,dnf官网,斗罗大陆神界传说充值,暗黑破坏神修改器,手游排行,冒险王2,梦幻西游宝宝进阶,苹果7,手游最新游戏,乱世仙侠手游,魔法门之英雄无敌,穿越言情小说,斗罗大陆之兽神,最新三国游戏,仙侠类手游排行榜,新斗罗大陆手游阵容,卡牌游戏三国杀,很纯很暧昧小说,史莱克七怪,梦幻西游新,攻城三国游戏,斗罗大陆成神之路漫画,rpg手机游戏,手机版梦幻西游官网,手游交易平台,末日求生,情侣仙侠游戏,二次元卡牌游戏,唯美仙侠手游,一起来冒险手游,大主宰漫画,斗罗大陆四圣兽传说,名将三国手游,斗罗大陆神界传说,三国类型游戏,打怪升级的手游,仙侠电视剧,免费回合制手游游戏,梦幻西游手游九游,捕鱼游戏开发,新修仙网游,天龙八部手游所有礼包,战舰世界爱宕,剑侠情缘手游手游,热血帝王三国,免费小说大全,征途2手游攻略,暗黑2版本,天龙八部手游开服公告,大话西游装备,大话西游手游无限仙玉,两副牌斗地主,dnf剑神,暗黑2套装,手游网游,挂机三国游戏,天龙八部礼包大全,手游网络游戏,征服单机游戏,rpg角色扮演手游,蜀山战纪,东方仙侠,魔兽世界壁纸,斗罗大陆3龙神传说,剑魂,征途游戏,新修仙网游,的手游,解放战争三大战役,热血修仙游戏,龙王传说吧,混沌剑神,关于手游三国卡牌游戏,寻仙手游,大话西游3,阴阳师手游,动漫大全,手游版梦幻西游,西游单机版礼包,斗破苍穹txt,斗罗大陆2免费阅读全文,梦幻西游手游礼包怎么兑换,天龙八部小说金庸,大话西游单机版,地狱边境,新斗罗大陆,三国单机游戏,绝世武神,小米,梦幻西游手游九游,冒险岛手游双刀尖兵,手游武侠版,暗黑剑士,斗罗3龙王传说小说,手游三国名将,手机游戏单机版,斗罗大陆之三生武魂,手游卡牌游戏大全,dnf加点模拟器,三国手游,手游修仙狂徒,游戏三张牌下载,魂斗罗归来魂斗罗战舰,仙侠手游排行榜前十名,大话西游伏魔,剑神诀手游下载,水浒q传,冒险岛2吧,类似阴阳师的抽卡游戏,dnf剑魂,2018适合平民玩的手游,斗罗大陆神界传说,斗罗大陆听书,凡修仙,斗罗大陆手游官网,大话西游人族,怒战三国手游,单机游戏三国,大话西游手游神天兵伙伴,西游变态版官网,航海王剧场版,suv,刀塔英雄吧,多玩游戏,大型手机游戏,斗罗大陆3手游礼包,梦幻西游武神坛,大型3d手游,仙侠手游职业武器长枪,修仙狂徒女主,dnf游戏充值,斗罗大陆网游下载,斗罗大陆漫画免费,斗罗大陆之地煞星,安卓手机游戏下载,好玩的卡牌网游,镇魂,武魂传说,游戏排行榜大型网络游戏,有没有打怪的手游,手游仙侠角色手游,仙侠角色扮演手游,地下城与勇士游戏,最新修仙手游,魔兽塔防,点将三国,仙侠萌主手游,微信,神奇宝贝图片,斗罗大陆3小说免费阅读全文,卡牌三国游戏,动漫头像,挂机三国游戏,仙侠手游情侣名,兰博基尼,斗破苍穹2安卓版,消防工程师,火影格斗,魔域第一土豪,无道具的网页游戏,暗黑破坏神单机,手游手游手游,网游之三国领主模式,啪啪,通缉战争之刺,大型仙侠游戏排行榜,梦幻古龙,梦幻西游发号,红警共和国之辉,凡人修真2公益服,冒险岛2吧,三国武将卡牌游戏,荒岛求生,鱼竿,暗黑剑士,斗罗大陆2小说,仙侠电影,大话西游经典台词,手游版最新传奇,战争大流氓,魂斗罗归来手游下载,斗罗大陆小说,冒险岛单机版,焚天之怒,三国类手游,播放器,二次元手机游戏大全,4399游戏盒,梦幻西游手游倒金币,丧尸游戏,斗罗大陆2绝世唐门游戏下载,卡牌游戏圣斗士星矢,神兽,斗罗大陆3,dnf官方手游,诛仙手游各种礼包,大剑仙,大话西游人族,仙侠手游攻略,电子书下载,斗罗,斗罗大陆3手游,魂斗罗归来手游下载,刀塔传奇游戏攻略,仙剑奇缘,王者荣耀体验服账号,冒险岛手游哪里打装备,韩服手游,网站,有没有新的手游,三国梦想,斗罗大陆3龙神传说,超级魂斗罗30条命,凡人修仙全文阅读,单机三国群英传,游戏二次元游戏,刀塔传奇公会战,小说软件,仙侠游戏啪啪,名将三国,斗罗大陆 漫画,斗罗大陆之枪神斗罗,地下城与勇士单机版,斗罗大陆的封号斗罗,征途游戏,烈焰手游手游礼包,小说穿越,三国卡牌策略手游,冒险岛人马,修仙小游戏下载,在线视频,幸存者,三国五虎将,圣斗士手游,龙之谷,战争之人,斗罗大陆漫画,街机,天龙八部手游九游,qq邮箱,三国战争手游,天龙八部官网礼包领取,仙侠修仙手游角色,极道天魔,超次元战姬手游,斗罗大陆h,魂斗罗游戏,游戏足球,国战的网页游戏,秦时明月2,坦克大战,三国武将游戏下载,看大片,手游杀神,新大主宰,手机游戏大游戏,有声小说回到明朝当王爷,游戏仙侠小说,梦幻西游本子,枪神纪,大话仙侠变态手游,天龙八部刷怪脚本,那个卡牌手游最好玩,斗罗大陆3最新章节,捕鱼比赛,恋爱养成小游戏,类似暗黑的手机游戏,3d魔幻手游,射击游戏,回合rpg游戏,英雄三国,斗罗大陆听书,游戏礼包,全文免费阅读,搞笑仙侠小说,丧尸游戏,百度斗罗大陆手游礼包,同城异性约会,多玩游戏,微信借钱一分钟到账,仙侠手游神武,养成游戏,超次元游戏手游,手游三国群英传,网游之网游之,凡人修仙之风云再起,宠物手游,剑神诀,仙侠江湖手游,手游逍遥西游手游,仙侠手游攻略,三国第一猛将并非吕布,手游三国名将攻略,梦仙侠,手游斗罗大陆变态版,手游网络游戏,暗黑2重制版,小说阅读软件,斗罗大陆之三生武魂,卡牌游戏手机游戏,苍穹变,明朝初年,灭霸神魔录手游,仙侠游戏师徒,三国关羽游戏,三国武将,梦幻西游手游九游,奥特曼格斗进化,僵尸求生,4399游戏盒,战争的游戏,苹果5s,妖怪正传,新大主宰,动漫,魔兽卡牌游戏,美女图,斗罗大陆电影,日本动画,仙侠世界,三国梦想,重生之最强剑神,斗罗大陆神界传说2,战斗吧剑灵,大话西游音乐,天龙八部领武圣卡,奇迹,黄色片,镇魂,点将三国,好玩的卡牌游戏排行,梦幻西游兽决三不要,手游大作,小说阅读器,dnf征战者刷图加点,英雄联盟手机游戏,冒险岛手游官网,大话西游手游神天兵伙伴,罗成斗罗大陆,绝地求生全军出击,爆装备手游,斗罗大陆后续,官方梦幻西游手游,梦幻江湖,三国卡牌策略手游,军师三国手游,斗罗大陆龙王传说3,宠物手游,大话修仙变态,丧尸来了,修仙 游戏,小说全本免费,梦幻西游手游最便宜神兽,仙侠修真,三国类型游戏"]

  producttypes: []
  education: 0
  keywordsExtend: 1
  newInterests: 0
  iosVersion: 0
  androidVersion: 0
  excludeTrans: 0
  region: 9999999

  bgtctltype: 1  # 0、1、2，匀速、标准、加速
  schedule: [{
             "weekDay": 3,
             "startHour": 5,
             "endHour": 10},
            {
             "weekDay": 4,
             "startHour": 5,
             "endHour": 10}]
